name: advanced
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.4.1
  archive: "^3.1.2"
  pointycastle: ^3.1.3
  http: ^0.13.3
  sqljocky5: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
